#!/bin/sh

/bin/openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj "/CN=Eaton" -keyout ${SYNOPKG_PKGDEST}/bin/key.pem -out ${SYNOPKG_PKGDEST}/bin/cert.pem

ln -s /var/packages/${SYNOPKG_PKGNAME}/scripts/start-stop-status /usr/local/etc/rc.d/ipp-linux.sh
